In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Генерация данных для примера
np.random.seed(42)
X = np.random.rand(40000, 3)
y = (X.sum(axis=1) > 1.5).astype(int)  # Пример: если сумма трех чисел больше 1.5, то выход 1, иначе 0

# Разделение данных на обучающие и тестовые
train_size = int(0.8 * X.shape[0])
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

print(X_train[0:10])
# Создание модели
model = Sequential([
    Dense(16, input_shape=(3,), activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Компиляция модели
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Обучение модели
model.fit(X_train, y_train, epochs=3, batch_size=32, validation_split=0.2)

# Оценка модели
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

# Пример предсказания
example = np.array([[0.5, 0.5, 0.6]])
prediction = model.predict(example)
print(f"Prediction for {example}: {prediction[0][0]:.4f}")


[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]]
Epoch 1/3


2024-05-20 21:53:55.969088: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


800/800 [==============================] - 6s 6ms/step - loss: 0.2845 - accuracy: 0.8982 - val_loss: 0.0981 - val_accuracy: 0.9886
Epoch 2/3
800/800 [==============================] - 4s 5ms/step - loss: 0.0732 - accuracy: 0.9866 - val_loss: 0.0588 - val_accuracy: 0.9866
Epoch 3/3
250/250 [==============================] - 1s 3ms/step - loss: 0.0433 - accuracy: 0.9910
Test Accuracy: 0.9910
1/1 [==============================] - 0s 104ms/step
Prediction for [[0.5 0.5 0.6]]: 0.9285


In [11]:
import numpy as np

def replace_99999_with_random(X):
    # Создаем маску, которая находит все элементы, равные 99999.0
    mask = (X == 99999.0)
    # Заменяем все элементы, которые равны 99999.0, на случайные значения в диапазоне от 2.0 до 4.0
    X[mask] = np.float32(np.random.uniform(2.0, 4.0, size=np.sum(mask)))
    return X

# Пример использования функции
X = np.array([[10900, 99999.0, 11100],
              [10800, 0.11979, 97000],
              [46000, 99999.0, 10800],
              [10800, 0.11979, 97000]])
print("До замены:")
print(X)

X = replace_99999_with_random(X)
print("\nПосле замены:")
print(X)


До замены:
[[1.0900e+04 9.9999e+04 1.1100e+04]
 [1.0800e+04 1.1979e-01 9.7000e+04]
 [4.6000e+04 9.9999e+04 1.0800e+04]
 [1.0800e+04 1.1979e-01 9.7000e+04]]

После замены:
[[1.09000000e+04 3.48075891e+00 1.11000000e+04]
 [1.08000000e+04 1.19790000e-01 9.70000000e+04]
 [4.60000000e+04 2.68808413e+00 1.08000000e+04]
 [1.08000000e+04 1.19790000e-01 9.70000000e+04]]


In [12]:
for i in range(20):
    print(np.random.uniform(0.0001, 0.05))

0.038070334065376625
0.019030896975480015
0.008833227806582463
0.04266571278263416
0.0026879728444077385
0.018342032322360497
0.033659683996508975
0.04432953982602454
0.008139178769019043
0.004893137804048526
0.015176673793069877
0.012883891313127779
0.03474273774034883
0.011959543774375598
0.031236366610212014
0.03283472644519928
0.0402986557099916
0.03021081768419995
0.046057058913210054
0.034635622185700786
